name: caneandtender
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  uuid: ^4.5.2
  pinput: ^6.0.1
  fluttertoast: ^9.0.0
  lottie: ^3.1.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # âœ… ASSETS REGISTERED HERE
  assets:
    - assets/
