name: caneandtender
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  uuid: ^4.5.2
  pinput: ^6.0.1
  fluttertoast: ^8.2.14
  lottie: ^3.1.0

  # ğŸ—ºï¸ Google Maps
  google_maps_flutter: ^2.6.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1

  provider: ^6.1.5+1
  razorpay_flutter: ^1.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.7
  video_player: ^2.8.1
  chewie: ^1.7.1

flutter:
  uses-material-design: true

  # âœ… ASSETS REGISTERED HERE
  assets:
    - assets/images/
    - assets/logo/
    - assets/Sugarcane_and_Coconut_Juice_Video.mp4
    
